spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: root
  rabbitmq:
    addresses: 127.0.0.1
    port: 5672
    username: guest
    password: guest

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mappers/*.xml

logging:
  pattern:
    console: "[%thread] %-5level %logger{36} - %msg%n"

wx:
  appId: yours
  mchId: yours
  mchKey: yours
  notifyUrl: http://qvrbfn.natappfree.cc/pay/notify
  returnUrl: http://127.0.0.1

alipay:
  appId: yours
  privateKey: "yours"
  publicKey: "yours"
  notifyUrl: http://qvrbfn.natappfree.cc/pay/notify
  returnUrl: http://127.0.0.1
  © 2020 GitHub, Inc.
